<!DOCTYPE html>
<html lang="en"><head>
<script src="Presentation_J_files/libs/clipboard/clipboard.min.js"></script>
<script src="Presentation_J_files/libs/quarto-html/tabby.min.js"></script>
<script src="Presentation_J_files/libs/quarto-html/popper.min.js"></script>
<script src="Presentation_J_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="Presentation_J_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Presentation_J_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="Presentation_J_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Charles Gao Andrew Hwang Jason Huffstutter Andrew Hahm">
  <title>Legalization &amp; Cannabis Use</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="Presentation_J_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="Presentation_J_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="Presentation_J_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link href="Presentation_J_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="Presentation_J_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="Presentation_J_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="Presentation_J_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Legalization<br>&amp; Cannabis Use</h1>
  <p class="subtitle">Stats 115 Final Project</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Charles Gao<br>Andrew Hwang<br>Jason Huffstutter<br>Andrew Hahm 
</div>
</div>
</div>

</section>
<section id="our-research-question" class="slide level2">
<h2>Our Research Question</h2>
<ul>
<li>Was early state-level marijuana legalization in 2012 (Washington, Colorado) and 2014 (Alaska, Oregon) associated with higher marijuana-use rates among ages 18–25, beyond the broader national trend?</li>
</ul>
</section>
<section id="background-motivation" class="slide level2">
<h2>Background &amp; Motivation</h2>
<div style="font-size: 0.75em;">
<p>Why should we care about this topic?</p>
<ul>
<li><p>Marijuana legalization is a policy issue in the United States that goes beyond red/blue politics, as it reflects family dynamics, community experiences, and personal values.</p></li>
<li><p>A key concern is whether legalization is associated with significantly higher marijuana use, especially among young adults.</p></li>
</ul>
<p>Who will these results help in the future?</p>
<ul>
<li><p>Policymakers can use these results to better understand how marijuana regulation can affect younger demographics.</p></li>
<li><p>Public health groups and schools can use this information to better educate and improve prevention efforts.</p></li>
<li><p>Individuals can gain knowledge to create more informed opinions.</p></li>
</ul>
</div>
</section>
<section id="dataset-overview" class="slide level2">
<h2>Dataset Overview</h2>
<div style="font-size: 0.7em;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Dimensions: 867 observations × 53 variables</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Years: 2002 - 2018 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>States: 51 (includes Washington D.C.)</code></pre>
</div>
</div>
<p><strong>Key Variables:</strong></p>
<ul>
<li><strong>Demographics</strong>: State, Year, Population by age group</li>
<li><strong>Substances</strong>: Marijuana, Tobacco, Alcohol, Cocaine</li>
<li><strong>Metrics</strong>: Totals (counts) and Rates (per 1000 people)</li>
<li><strong>Time frames</strong>: Past month, past year usage</li>
</ul>
<p><strong>Age Groups:</strong></p>
<ul>
<li>12-17 (adolescents)</li>
<li>18-25 (young adults)</li>
<li>26+ (adults)</li>
</ul>
</div>
</section>
<section id="marijuana-trends-by-age" class="slide level2">
<h2>Marijuana Trends by Age</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-3-1.png" width="1152" class="r-stretch"><div style="font-size: 60%;">
<p>The 18–25 age group shows an increasing rate over time and remains significantly higher than the other two age groups.</p>
</div>
</section>
<section id="tobacco-trends" class="slide level2">
<h2>Tobacco Trends</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-4-1.png" width="1152" class="r-stretch"><div style="font-size: 60%;">
<p>The 18–25 age group shows the highest tobacco usage rate. Rates for all three age groups gradually decline over time, but at different speeds, with the 18–25 group eventually converging with the 26+ group.</p>
</div>
</section>
<section id="states-ranked-by-marijuana-use-2018" class="slide level2">
<h2>States Ranked by Marijuana Use (2018)</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-5-1.png" width="960" class="r-stretch"></section>
<section id="correlation-matrix" class="slide level2">
<h2>Correlation Matrix</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-6-1.png" width="1152" class="r-stretch"><div style="font-size: 0.8em;">
<p><strong>Two distinct camps:</strong> Cocaine &amp; Marijuana users (r = 0.55) vs Alcohol &amp; Tobacco users (r = 0.73)</p>
<p><strong>Key insight:</strong> Marijuana and Tobacco negatively correlated (r = -0.27) - both are smoking activities, individuals choose one over the other</p>
</div>
</section>
<section id="all-substance-trends" class="slide level2">
<h2>All Substance Trends</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-7-1.png" width="1152" class="r-stretch"></section>
<section id="question-2-marijuana-legalization" class="slide level2">
<h2>Question 2: Marijuana Legalization</h2>
<p><strong>Was early state-level marijuana legalization in 2012 (Washington, Colorado) and 2014 (Alaska, Oregon) associated with higher marijuana-use rates among ages 18–25, beyond the broader national trend?</strong></p>
<p>Our exploratory analysis suggested that marijuana use among <strong>18–25-year-olds</strong> rose in the years following legalization. We then asked whether early-adopter states experienced an additional post-legalization increase relative to the broader national pattern, or whether usage was simply rising along with the national trajectory.</p>
</section>
<section id="legalization-timeline" class="slide level2">
<h2>Legalization Timeline</h2>
<div style="font-size: 0.75em;">
<p><strong>Early Adopter States:</strong></p>
<ul>
<li><strong>2012</strong>: Washington &amp; Colorado legalized recreational marijuana</li>
<li><strong>2014</strong>: Alaska &amp; Oregon legalized recreational marijuana</li>
</ul>
<p><strong>Our Analysis:</strong></p>
<p>Compare marijuana usage rates in these 4 early-adopter states vs.&nbsp;all other states to identify:</p>
<ol type="1">
<li>Pre-legalization baseline differences</li>
<li>Post-legalization divergence (if any)</li>
<li>Whether early-adopter states showed larger post-legalization increases than other states</li>
</ol>
</div>
</section>
<section id="marijuana-rates-early-adopters-vs-others" class="slide level2">
<h2>Marijuana Rates: Early Adopters vs Others</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-8-1.png" width="1152" class="r-stretch"></section>
<section id="pre-vs-post-legalization-trends" class="slide level2">
<h2>Pre vs Post Legalization Trends</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-9-1.png" width="1152" class="r-stretch"></section>
<section id="rate-of-change-analysis" class="slide level2">
<h2>Rate of Change Analysis</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-10-1.png" width="1152" class="r-stretch"></section>
<section id="question-2-findings" class="slide level2">
<h2>Question 2: Findings</h2>
<div style="font-size: 0.6em;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Pre-2012 Average Rates (per 1000):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Early Adopters: 220.58 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Other States: 174.73 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Difference: 45.85 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Post-2014 Average Rates (per 1000):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Early Adopters: 294.44 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Other States: 211.56 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Difference: 82.88 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Change from Pre-2012 to Post-2014:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Early Adopters: + 73.86 ( 33.5 % increase)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Other States: + 36.83 ( 21.1 % increase)</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Larger increases in early-adopter states are consistent with a positive post-legalization association, but do <strong>not by themselves establish causality</strong></li>
<li>Similar increases across groups would be more consistent with a broader national trend</li>
<li>Baseline differences suggest early-adopter states may already have had stronger underlying demand or different pre-existing preferences</li>
</ul>
</div>
</section>
<section id="question-2-conclusion" class="slide level2">
<h2>Question 2: Conclusion</h2>
<div style="font-size: 0.6em;">
<p><strong>Pre-legalization (before 2012):</strong></p>
<ul>
<li><p>Early adopters: 220.6 per 1000</p></li>
<li><p>Other states: 174.7 per 1000</p></li>
<li><p>Early-adopter states already had substantially higher marijuana-use rates before legalization</p></li>
</ul>
<p><strong>Post-legalization (2014+):</strong></p>
<ul>
<li><p>Early adopters: 294.4 per 1000</p></li>
<li><p>Other states: 211.6 per 1000</p></li>
<li><p>The gap widened further in the post-legalization period</p></li>
</ul>
<p><strong>Key Pattern:</strong></p>
<ul>
<li><p>Early adopters: <strong>33.5% increase</strong> (+73.9 per 1000)</p></li>
<li><p>Other states: <strong>21.1% increase</strong> (+36.8 per 1000)</p></li>
</ul>
</div>
</section>
<section id="question-2-important-caution" class="slide level2">
<h2>Question 2: Important Caution:</h2>
<div style="font-size: 0.7em;">
<p>Because early-adopter states already had higher baseline usage and appear to have been increasing faster even before legalization, this comparison does <strong>not by itself establish a causal effect</strong>.</p>
<p>The post-legalization divergence is consistent with legalization being associated with higher marijuana-use rates, but part of the difference may also reflect pre-existing state-level preferences and trends.</p>
<p><strong>Answer:</strong> Early-adopter states experienced larger increases in marijuana use among ages 18–25 than other states, but the evidence here should be interpreted as <strong>associational rather than definitively causal</strong>. Legalization may have contributed to the increase, but these states were already different before legalization.</p>
</div>
</section>
<section id="statistical-testing-did-legalization-matter" class="slide level2">
<h2>Statistical Testing: Did Legalization Matter?</h2>
<div style="font-size: 0.7em;">
<p><strong>Modeling Strategy:</strong></p>
<p>Because legalization occurred at different times across the treated states, we define a <strong>state-specific post-legalization indicator</strong>:</p>
<ul>
<li><p><span class="math inline">\(Post_{it}=1\)</span> if state <span class="math inline">\(i\)</span> is in a legalized period in year <span class="math inline">\(t\)</span></p></li>
<li><p><span class="math inline">\(Post_{it}=0\)</span> otherwise</p></li>
</ul>
<p>This means <span class="math inline">\(Post_{it}\)</span> already represents the treatment exposure for early-adopter states after legalization. It is effectively a <strong>treated × post</strong> indicator, so we do <strong>not</strong> need a separate interaction term such as <span class="math inline">\(EarlyAdopter_i \times Post_t\)</span> in this model.</p>
</div>
</section>
<section id="interpretation-goal" class="slide level2">
<h2>Interpretation Goal:</h2>
<div style="font-size: 0.7em;">
<p>We estimate whether marijuana-use rates in ages 18–25 were higher in treated states <strong>after their legalization year</strong>, while also accounting for:</p>
<ul>
<li>year-specific national effects shared across states</li>
<li>persistent baseline differences across states</li>
</ul>
</div>
</section>
<section id="two-sample-t-test-on-growth-rates" class="slide level2">
<h2>Two-Sample t-test on Growth Rates</h2>
<div style="font-size: 0.75em;">
<p>Let’s run a simple t-test:</p>
<p><span class="math display">\[
H_0:\ \mu_{\text{Early growth}} = \mu_{\text{Other growth}}
\]</span></p>
<p><span class="math display">\[
H_1:\ \mu_{\text{Early growth}} &gt; \mu_{\text{Other growth}}
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Two-Sample t-test: Early Adopters vs Other States</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean growth Early Adopters: 34.9 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean growth Other States: 23.13 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: 0.85 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>p-value: 0.2249 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Conclusion: No statistically significant difference in average growth was detected</code></pre>
</div>
</div>
</div>
</section>
<section id="bayesian-approach-question-2" class="slide level2">
<h2>Bayesian Approach: Question 2</h2>
<p><strong>Why Bayesian?</strong></p>
<ul>
<li>Quantify <strong>uncertainty</strong> in the effect of legalization</li>
<li>Get <strong>probability distributions</strong> instead of just point estimates</li>
<li>Make probabilistic statements such as: “What is the probability that the post-legalization effect is positive?”</li>
<li>Incorporate <strong>prior knowledge</strong> about drug use trends</li>
</ul>
</section>
<section id="proposed-model" class="slide level2">
<h2>Proposed Model</h2>
<div style="font-size: 0.7em;">
<p><span class="math display">\[
Rate_{it} \sim \text{Normal}(\mu_{it}, \sigma)
\]</span></p>
<p><span class="math display">\[
\mu_{it} = \alpha_i + \lambda_t + \beta Post_{it}
\]</span></p>
</div>
<p><strong>Where:</strong></p>
<div style="font-size: 0.65em;">
<ul>
<li><span class="math inline">\(Rate_{it}\)</span> is the marijuana-use rate for state <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span></li>
<li><span class="math inline">\(\alpha_i\)</span> is the state-specific baseline level</li>
<li><span class="math inline">\(\lambda_t\)</span> is the year-specific effect shared by all states</li>
<li><span class="math inline">\(Post_{it}\)</span> is a state-specific post-legalization indicator</li>
</ul>
</div>
<p><strong>Why use year effects instead of a linear year trend?</strong></p>
<div style="font-size: 0.65em;">
<p>A single linear time term assumes marijuana-use rates changed at a constant national rate over time. Using year effects is more flexible: it allows each year to have its own national shift, which better captures non-linear changes in marijuana use over the sample period.</p>
</div>
</section>
<section id="important-note" class="slide level2">
<h2>Important Note:</h2>
<div style="font-size: 0.65em;">
<p>This is <strong>not</strong> a slope-interaction model such as <span class="math display">\[
Rate \sim Year + Group + Year \times Group
\]</span></p>
<p>Instead, the fitted model estimates a <strong>post-legalization level shift</strong> through <span class="math inline">\(Post_{it}\)</span>, while allowing each state to have its own baseline level through the random intercept <span class="math inline">\(\alpha_i\)</span>.</p>
</div>
</section>
<section id="model-interpretation" class="slide level2">
<h2>Model Interpretation</h2>
<div style="font-size: 0.6em;">
<p><strong>Key Parameter:</strong> <span class="math inline">\(β\)</span> (<span class="math inline">\(Post_{it}\)</span>)</p>
<p>If <span class="math inline">\(β &gt; 0\)</span>, then marijuana-use rates were higher in treated states during their post-legalization years, after accounting for:</p>
<ul>
<li>baseline differences across states through <span class="math inline">\(α_i\)</span></li>
<li>nationwide year-to-year shocks through <span class="math inline">\(λ_t\)</span></li>
</ul>
<p>Because <span class="math inline">\(Post_{it}\)</span> is defined separately for each state based on its own legalization year, it already serves as the treatment indicator for “treated state after legalization.”</p>
<p><strong>Parameter meanings:</strong></p>
<ul>
<li><span class="math inline">\(α_i\)</span>: state-specific baseline marijuana-use level</li>
<li><span class="math inline">\(λ_t\)</span>: year-specific national effect</li>
<li><span class="math inline">\(β\)</span>: additional post-legalization shift in treated states</li>
</ul>
</div>
</section>
<section id="model-interpretation-continued" class="slide level2">
<h2>Model Interpretation Continued</h2>
<div style="font-size: 0.6em;">
<p><strong>Model Note:</strong></p>
<p>This specification is more flexible than a linear time trend because it does not force national marijuana-use rates to move in a straight line over time.</p>
<p><strong>Posterior Predictive Checks:</strong></p>
<ul>
<li>Simulate replicated state-year rates from the posterior</li>
<li>Compare simulated values to observed trends over time</li>
<li>Check whether the model captures national year effects, state-level variation, and post-legalization shifts</li>
</ul>
</div>
</section>
<section id="mcmc-trace" class="slide level2">
<h2>MCMC Trace</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-15-1.png" width="960" class="r-stretch"><div style="font-size: 0.6em;">
<p>The traceplots show good mixing across chains</p>
</div>
</section>
<section id="mcmc-density-overlay" class="slide level2">
<h2>MCMC Density Overlay</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-16-1.png" width="960" class="r-stretch"><div style="font-size: 0.6em;">
<p>Density overlays are quite consistent across chains. Intercept chains showed slight variation, but overall the posterior simulation converged well and the MCMC samples are reliable for inference.</p>
</div>
</section>
<section id="posterior-predictive-check" class="slide level2">
<h2>Posterior Predictive Check</h2>

<img data-src="Presentation_J_files/figure-revealjs/unnamed-chunk-17-1.png" width="960" class="r-stretch"><div style="font-size: 0.6em;">
<p>Our simulated data from the posterior match the observed distribution and trend quite well. The model captures the main structure of the marijuana-use data reasonably well.</p>
</div>
</section>
<section id="bayesian-analysis-results" class="slide level2">
<h2>Bayesian Analysis Results</h2>
<p><strong>Credible Intervals</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5%     97.5%
(Intercept) 168.28882 195.14296
Post         29.02367  46.99303</code></pre>
</div>
</div>
<p><strong>Posterior probability</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="bayesian-analysis-results-continued" class="slide level2">
<h2>Bayesian Analysis Results Continued</h2>
<div style="font-size: 0.7em;">
<p><strong>Posterior Summary:</strong></p>
<ul>
<li><p><span class="math inline">\(95\%\)</span> credible interval for <span class="math inline">\(β\)</span> (<span class="math inline">\(Post_{it}\)</span>): <span class="math inline">\([29.02,\ 46.99]\)</span></p></li>
<li><p><span class="math inline">\(P(β &gt; 0 \mid data) = 1.00\)</span></p></li>
</ul>
<p><strong>Interpretation:</strong> After accounting for state-level baseline differences and year-specific national effects, the estimated post-legalization coefficient remains clearly positive. Under this model, post-legalization years in treated states were associated with an additional increase of about 29 to 47 rate points in marijuana-use rates among ages 18–25. This estimate reflects a post-legalization level shift rather than a different slope over time.</p>
</div>
</section>
<section id="question-2-comparing-the-approaches" class="slide level2">
<h2>Question 2: Comparing the Approaches</h2>
<div style="font-size: 0.6em;">
<p><strong>Descriptive Analysis:</strong></p>
<ul>
<li>Early-adopter states showed larger increases in marijuana-use rates than other states</li>
<li>However, these states also had higher baseline usage before legalization</li>
</ul>
<p><strong>Frequentist Test:</strong></p>
<ul>
<li>The two-sample t-test found higher average growth in early-adopter states</li>
<li>However, the difference was not statistically significant</li>
</ul>
<p><strong>Bayesian Model:</strong></p>
<ul>
<li>The model controls for state-level baseline differences and year-specific national effects</li>
<li>The post-legalization indicator <span class="math inline">\(Post_{it}\)</span> remained strongly positive: <span class="math inline">\(95\%\)</span> credible interval <span class="math inline">\([29.02,\ 46.99]\)</span></li>
<li><span class="math inline">\(P(β &gt; 0 \mid data) = 1.00\)</span></li>
</ul>
</div>
</section>
<section id="question-2-comparing-the-approaches-continued" class="slide level2">
<h2>Question 2: Comparing the Approaches Continued</h2>
<div style="font-size: 0.7em;">
<p><strong>Key Insight:</strong></p>
<p>Across all three approaches, early-adopter states showed larger post-legalization increases in marijuana-use rates among ages 18–25. The Bayesian model provides the clearest evidence of a positive post-legalization <strong>association</strong>, even after accounting for persistent state differences and flexible year-to-year national shifts. At the same time, because early-adopter states already differed before legalization, the result should be interpreted as strongly suggestive rather than definitively causal.</p>
</div>
</section>
<section id="where-could-we-go-from-here" class="slide level2">
<h2>Where could we go from here?</h2>
<ul>
<li><p>We would collect more detailed data, such as county-level or individual-level data, instead of only state-level averages.</p></li>
<li><p>We would use stronger methods to study causality and better separate the effect of legalization from pre-existing state differences.</p></li>
<li><p>We would also study other factors like dispensary access, advertising, local policies, and differences across different demographics instead of just age</p></li>
</ul>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="Presentation_J_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="Presentation_J_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="Presentation_J_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="Presentation_J_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="Presentation_J_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="Presentation_J_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="Presentation_J_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="Presentation_J_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="Presentation_J_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="Presentation_J_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>